### ISSUE TITLE
Feature Request - Hierarchical Display of Taxonomy Terms 

### ISSUE THREAD

**Issue by block4** [dcavins/bp-docs-taxonomies#2]
The terms are now showing up as check boxes in alphabetical order without regard to hierarchy.  This means that child terms are not appearing under parent terms.  If a child term and a main term both have the same label, then they will appear one above the other rather than the child appearing under its parent. Could the display be rearranged so that the child terms appear under the parent terms (and indented a bit) rather than all terms appearing in alphabetical order?

Also, in some cases, a list of checkboxes may take up a loooooooot of real estate on a page.  For such occasions would it be possible to allow the admin to choose to have the terms display in a  multiselect dropdown?

**Comment by dcavins** [comment]
HI @block4-

Hierarchical term handling was added in 6c07af9d55d7. Thanks for the suggestion!

Re other form elements, can you come up with something other than a multiselect dropdown? I'm loathe to turn that sad form element loose on the world. :)

-David

**Comment by block4** [comment]
Hi, @dcavins -

The update works quite nicely.  Now the terms display in hierarchical order.  Thank you! The update also seems to have solved the error that was appearing a doc was saved with a term selected.

**Comment by block4** [comment]
Closing issue.
